version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=dev
      - MONGO_URI=mongodb://admin:password@mongodb:27017/event-reward?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongodb
    command: yarn start:auth
    restart: always

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=dev
      - MONGO_URI=mongodb://admin:password@mongodb:27017/event-reward?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongodb
    command: yarn start:gateway
    restart: always

  gateway-swagger:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile-swagger
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=dev
    depends_on:
      - gateway
    restart: always

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=dev
      - MONGO_URI=mongodb://admin:password@mongodb:27017/event-reward?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongodb
    command: yarn start:event
    restart: always

volumes:
  mongodb_data: