version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=live
      - MONGO_URI=mongodb://admin:password@mongodb:27017/event-reward?authSource=admin
      - JWT_SECRET=secret
    depends_on:
      - mongodb
    command: ["node", "dist/apps/auth/src/main.js"]
    restart: always

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=live
      - MONGO_URI=mongodb://admin:password@mongodb:27017/event-reward?authSource=admin
      - JWT_SECRET=secret
      - AUTH_SERVICE_URL=http://auth:3001
      - EVENT_SERVICE_URL=http://event:3003      
    depends_on:
      - mongodb
    command: ["node", "dist/apps/gateway/src/main.js"]
    restart: always

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=live
      - MONGO_URI=mongodb://admin:password@mongodb:27017/event-reward?authSource=admin
      - JWT_SECRET=secret
    depends_on:
      - mongodb
    command: ["node", "dist/apps/event/src/main.js"]
    restart: always

  gateway-swagger:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile-swagger
    ports:
      - "8080:37812"
    environment:
      - NODE_ENV=live
    depends_on:
      - gateway
    restart: always

volumes:
  mongodb_data: