/**
 * @packageDocumentation
 * @module api.functional.api.v1.rewards.histories.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { RewardHistoryResponseDto } from "../../../../../../../libs/shared/src/dtos/reward.dto";

/**
 * 현재 로그인한 사용자의 보상 이력 조회
 *
 * @tag rewards
 * @security bearer
 * @summary 현재 로그인한 사용자의 보상 이력을 조회합니다
 *
 * @controller RewardsController.getMyRewardHistory
 * @path GET /api/v1/rewards/histories/me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMyRewardHistory(
  connection: IConnection,
): Promise<getMyRewardHistory.Output> {
  return PlainFetcher.fetch(connection, {
    ...getMyRewardHistory.METADATA,
    template: getMyRewardHistory.METADATA.path,
    path: getMyRewardHistory.path(),
  });
}
export namespace getMyRewardHistory {
  export type Output = Primitive<Array<RewardHistoryResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/rewards/histories/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/rewards/histories/me";
}
