/**
 * @packageDocumentation
 * @module api.functional.api.v1.actions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as mock from "./mock";
