# Base Layer
FROM node:18-alpine AS base

WORKDIR /app

COPY package.json yarn.lock ./

# Dependencies Layer
FROM base as deps
RUN apk add g++ make py3-pip
RUN ["yarn", "install", "--frozen-lockfile"]

# Build Layer
FROM deps as build
ENV NODE_OPTIONS="--max-old-space-size=8192"
ENV APP_MAIN_FILE_DIR=dist
COPY . .

EXPOSE 37812

ENTRYPOINT ["yarn", "start:swagger"]
